// GENERATED by @edgedb/generate v0.0.8
// Run 'npx @edgedb/generate queries --file' to re-generate

import type {Executor} from "edgedb";

export async function getTransactions(client: Executor): Promise<{
  "id": string;
  "transaction_date": Date;
  "amount": number;
  "name": string;
  "transaction_type": string;
}[]> {
  return client.query(`select Transaction {
  id,
  transaction_date,
  amount,
  name,
  transaction_type
};`);
}